-- Insert more comprehensive Singapore senior benefits
INSERT INTO benefits (title, summary, description, eligibility_status, categories, source_url, apply_deadline) VALUES
('Age Well SG Programme', 'National initiative to support seniors aging actively in the community', 'Age Well SG is a national programme led by MOH, MND and MOT to support seniors to age well in their homes and their communities. It includes health screening, active ageing programs, and community support services.', 'ELIGIBLE', ARRAY['health', 'community'], 'https://www.agewellsg.gov.sg/', NULL),

('Silver Guardian Programme', 'Community-based support for vulnerable seniors', 'The Silver Guardian Programme provides community volunteers who check on vulnerable seniors regularly, offering social support and early intervention when needed. Part of the national aging-in-place strategy.', 'ELIGIBLE', ARRAY['community', 'support'], 'https://www.moh.gov.sg/newsroom/speech-by-mr-ong-ye-kung--minister-for-health-at-launch-of-the-silver-guardian-programme-on-5-april-2024', NULL),

('Merdeka Generation Benefits', 'Comprehensive healthcare subsidies for Merdeka Generation seniors', 'Special healthcare benefits for Singapore Citizens born from 1950 to 1959, including additional subsidies for outpatient care, specialist care, and health screening.', 'MAYBE', ARRAY['healthcare', 'subsidies'], 'https://www.moh.gov.sg/newsroom/launch-of-additional-outpatient-care-subsidies-for-merdeka-generation-seniors-and-enhanced-community-health-assist-scheme', NULL),

('Senior Activity Centre Support', 'Social and recreational activities at HDB void decks', 'Drop-in centres located at void decks of HDB rental flats providing social activities, meals, health talks, and support services for seniors in a familiar neighborhood environment.', 'ELIGIBLE', ARRAY['social', 'community'], 'https://www.healthhub.sg/a-z/medical-and-care-facilities/senior_activity_centre', NULL),

('Active Ageing Centre Programs', 'Comprehensive wellness programs for healthy aging', 'Active Ageing Centres provide fitness classes, educational workshops, social activities, and health screenings to help seniors stay physically and mentally active in their golden years.', 'ELIGIBLE', ARRAY['fitness', 'wellness'], 'https://pcs.org.sg/services/seniors/active-ageing-centre/', NULL),

('CHAS Chronic Conditions Support', 'Enhanced subsidies for chronic disease management', 'Community Health Assist Scheme provides ongoing support for managing chronic conditions like diabetes, hypertension, and high cholesterol through subsidized treatments at participating clinics.', 'ELIGIBLE', ARRAY['healthcare', 'chronic-care'], 'https://www.chas.sg/managing-your-chronic-conditions-using-chas', NULL);

-- Insert more comprehensive Singapore senior events
INSERT INTO events (title, summary, description, event_date, venue_name, venue_address, latitude, longitude, distance_km, eligibility_status, categories, organizer, registration_url) VALUES
('Active Ageing Fitness Class @ Toa Payoh', 'Low-impact aerobics and strength training for seniors', 'Join our weekly fitness class designed specifically for seniors. Includes gentle aerobics, strength training with resistance bands, and balance exercises. All fitness levels welcome.', '2024-08-26T02:00:00+00:00', 'Toa Payoh Active Ageing Centre', '179 Toa Payoh Central', 1.3329, 103.8503, 4.2, 'ELIGIBLE', ARRAY['fitness', 'wellness'], 'PCS Active Ageing Centre', 'https://pcs.org.sg/services/seniors/active-ageing-centre/'),

('Health Screening @ Ang Mo Kio', 'Comprehensive health check-up under Age Well SG', 'Free health screening including blood pressure, cholesterol, diabetes, and BMI checks. Part of the national Age Well SG programme to promote healthy aging.', '2024-08-27T01:00:00+00:00', 'Ang Mo Kio Polyclinic', '21 Ang Mo Kio Central 2', 1.3692, 103.8454, 1.5, 'ELIGIBLE', ARRAY['healthcare', 'screening'], 'Age Well SG', 'https://www.agewellsg.gov.sg/'),

('Silver Arts Workshop @ Jurong', 'Creative expression through traditional and modern arts', 'Explore your creativity through painting, calligraphy, and craft-making. Learn traditional Chinese painting techniques alongside modern art forms. Materials provided.', '2024-08-28T06:00:00+00:00', 'Jurong Community Club', '1 Jurong West Central 2', 1.3496, 103.7065, 8.5, 'ELIGIBLE', ARRAY['arts', 'culture'], 'Jurong Community Club', 'https://www.onepa.gov.sg/jurong-west'),

('Digital Literacy Workshop @ Bedok', 'Master smartphone and internet basics', 'Learn to use smartphones, WhatsApp, video calls, and online banking safely. Hands-on practice with devices provided. Part of the national digital inclusion initiative.', '2024-08-29T03:00:00+00:00', 'Bedok Community Centre', '850 New Upper Changi Rd', 1.3244, 103.9356, 15.0, 'ELIGIBLE', ARRAY['education', 'technology'], 'IMDA Digital for Life', 'https://www.imda.gov.sg/digitalforlife'),

('Intergenerational Cooking @ Chinatown', 'Traditional recipes shared across generations', 'Cook alongside young volunteers and share traditional Singaporean recipes. Learn about food heritage while teaching younger generations family cooking secrets.', '2024-08-30T04:00:00+00:00', 'Chinatown Complex', '335 Smith St', 1.2834, 103.8443, 6.2, 'ELIGIBLE', ARRAY['cooking', 'heritage'], 'Singapore Heritage Society', 'https://www.singaporeheritage.org'),

('Morning Exercise @ East Coast Park', 'Outdoor group exercise by the sea', 'Start your day with gentle stretching, qigong, and group walking along the beautiful East Coast coastline. Enjoy fresh sea air while staying active with friends.', '2024-08-31T23:00:00+00:00', 'East Coast Park', 'East Coast Park Service Rd', 1.3018, 103.9143, 18.5, 'ELIGIBLE', ARRAY['fitness', 'outdoor'], 'East Coast Community Club', 'https://www.onepa.gov.sg/east-coast'),

('Community Garden Workshop @ Sembawang', 'Learn sustainable urban farming techniques', 'Discover the joy of growing your own vegetables and herbs in urban community gardens. Learn composting, organic farming, and sustainable gardening practices.', '2024-09-01T08:00:00+00:00', 'Sembawang Community Garden', 'Sembawang Crescent', 1.4491, 103.8198, 12.8, 'ELIGIBLE', ARRAY['gardening', 'environment'], 'Sembawang Community Club', 'https://www.onepa.gov.sg/sembawang'),

('Health Talk @ Tampines Hub', 'Understanding and managing diabetes', 'Educational session on diabetes prevention and management, featuring healthcare professionals. Learn about diet, exercise, and medication management for better health outcomes.', '2024-09-02T06:30:00+00:00', 'Tampines Hub', '1 Tampines Walk', 1.3525, 103.9447, 12.3, 'ELIGIBLE', ARRAY['healthcare', 'education'], 'Health Promotion Board', 'https://www.hpb.gov.sg'),

('Cultural Heritage Walk @ Little India', 'Explore Singapore''s rich multicultural heritage', 'Guided walking tour through Little India''s historic streets, temples, and traditional shops. Learn about Singapore''s Indian heritage and cultural traditions.', '2024-09-03T08:30:00+00:00', 'Little India Heritage Trail', '48 Serangoon Rd', 1.3066, 103.8522, 7.1, 'ELIGIBLE', ARRAY['heritage', 'walking'], 'Singapore Heritage Society', 'https://www.singaporeheritage.org'),

('Technology Support Clinic @ Woodlands', 'One-on-one help with digital devices', 'Get personal assistance with your smartphone, tablet, or computer. Learn to use government digital services, online banking, and stay connected with family.', '2024-09-04T02:30:00+00:00', 'Woodlands Community Centre', '1 Woodlands Street 81', 1.4370, 103.7866, 15.2, 'ELIGIBLE', ARRAY['technology', 'support'], 'IMDA Digital for Life', 'https://www.imda.gov.sg/digitalforlife');